<li id="cmt2">
            <div class="cmt-info">
              <div class="gravatar"> <img alt="[field:name/]" src="http://zblogphp.neirong.org/zb_users/avatar/0.png" class="avatar avatar-45 photo" height="45" width="45"> </div>
              <div class="cmt-author"> <a href="http://www.boke8.net" rel="nofollow" target="_blank">[field:name/]</a> </div>
              <div class="cmt-meta"> 2015-06-27 23:39:11 </div>
              <div class="cmt-floor"> <a href="javascript:void(0);" onclick="zbp.comment.reply('2')">回复</a> </div>
            </div>
            <div class="cmt-con">[field:cont/]
            </div>
          </li>
        </ol>